from __future__ import annotations

from typing import Any

DEMO_USER_STATS = {
    "dang_xu_ly": 3,
    "dang_thuc_hien": 2,
    "da_giai_quyet": 8,
    "tong_yeu_cau": 24,
    "cho_phan_cong": 1,
    "thoi_gian_tb": "2.4h",
}

DEMO_TICKETS: list[dict[str, Any]] = [
    {
        "id": 1048,
        "title": "Máy in tầng 4 (Phòng Kế toán) không kết nối được mạng Wi-Fi",
        "category_code": "INCIDENT",
        "category_label": "Sự cố",
        "category_sub": "Phần cứng",
        "priority_code": "URGENT",
        "priority_label": "Khẩn cấp",
        "status_code": "IN_PROGRESS",
        "status_label": "Đang xử lý",
        "device_code": "PRN-ACC-04",
        "device_name": "Máy in HP LaserJet Pro M404dn",
        "device_location": "Tầng 4 - Tòa nhà A",
        "updated_time": "12 phút trước",
        "updated_note": "Đã gửi tin nhắn cập nhật",
        "tech_name": "Nguyễn Văn An",
        "tech_title": "Helpdesk L2",
        "tech_spec": "Chuyên viên IT L2 (Hạ tầng mạng)",
        "tech_role_short": "Kỹ thuật viên",
        "tech_initial": "NA",
        "tech_status": "Đang trực tuyến",
        "tech_email": "an.nguyen@helpdeskpro.enterprise",
        "tech_ext": "Ext 114",
        "created_at": "12/09/2026 lúc 09:42",
        "creator_name": "Trần Thị Mai (Phòng Kế toán)",
        "sla_status": "Đạt cam kết",
        "sla_detail": "Cam kết < 30 phút · Đã phản hồi sau 8 phút",
        "description": "Từ 09:00 sáng nay, máy in HP LaserJet tại góc phòng Kế toán (tầng 4) không thể nhận lệnh in từ bất kỳ máy tính nào trong phòng qua Wi-Fi 'Corp-Staff'. Đèn tín hiệu mạng trên máy in nhấp nháy đỏ liên tục.\n\nĐã thử khởi động lại cả máy in và router phụ nhưng vẫn báo trạng thái Offline trên máy tính. Phòng Kế toán đang cần in gấp chứng từ thuế và hóa đơn xuất kho cuối quý.",
        "attachments": [
            {
                "name": "error_screen_capture.png",
                "size": "1.2 MB",
                "type": "image",
                "action": "Xem trước ảnh",
            },
            {
                "name": "printer_network_log.txt",
                "size": "42 KB",
                "type": "text",
                "action": "Tệp nhật ký",
            },
        ],
        "history": [
            {
                "time": "10:15 (12 phút trước)",
                "author": "Nguyễn Văn An",
                "author_role": "Kỹ thuật viên",
                "is_tech_comment": True,
                "quote": "Đã kiểm tra switch mạng tầng 4. Phát hiện xung đột dải IP nội bộ sau đợt bảo trì mạng đêm qua. Đang tiến hành cấp IP tĩnh cố định cho máy in và nạp lại firmware driver.",
                "tags": ["Đang xử lý", "DHCP Release / IP Fix"],
            },
            {
                "time": "09:55",
                "action": "Chuyển trạng thái hệ thống",
                "text": "Hệ thống tự động: Chuyển từ 'Đã tiếp nhận' sang 'Đang xử lý'.",
                "is_tech_comment": False,
            },
            {
                "time": "09:50",
                "action": "Phân công kỹ thuật viên",
                "text": "Trưởng nhóm IT Helpdesk đã bàn giao ticket cho Nguyễn Văn An (Chuyên viên Hạ tầng & Phần cứng).",
                "is_tech_comment": False,
            },
            {
                "time": "09:42",
                "action": "Khởi tạo yêu cầu",
                "text": "Trần Thị Mai gửi yêu cầu hỗ trợ mới thành công. Mã định danh ticket ghi nhận #1048.",
                "is_tech_comment": False,
            },
        ],
    },
    {
        "id": 1045,
        "title": "Xin cấp quyền truy cập phần mềm ERP SAP phân hệ Kế toán",
        "category_code": "SERVICE_REQUEST",
        "category_label": "Yêu cầu dịch vụ",
        "category_sub": "Hệ thống ERP",
        "priority_code": "MEDIUM",
        "priority_label": "Trung bình",
        "status_code": "ASSIGNED",
        "status_label": "Đã tiếp nhận",
        "device_code": "PC-ACC-012",
        "device_name": "Dell OptiPlex 7090",
        "device_location": "Phòng Kế toán - Tầng 4",
        "updated_time": "2 giờ trước",
        "updated_note": "Chờ cấp license",
        "tech_name": "Lê Minh Tuấn",
        "tech_title": "SAP Specialist",
        "tech_role_short": "Hệ thống ERP",
        "tech_initial": "LT",
        "created_at": "12/09/2026 lúc 08:30",
        "creator_name": "Trần Thị Mai (Phòng Kế toán)",
        "description": "Nhân viên mới cần cấp tài khoản phân hệ Kế toán tài chính FI/CO để nhập chứng từ tháng.",
    },
    {
        "id": 1041,
        "title": "Bảo trì định kỳ và thay pin chuột/bàn phím không dây phòng kế toán",
        "category_code": "MAINTENANCE",
        "category_label": "Bảo trì",
        "category_sub": "Thiết bị cá nhân",
        "priority_code": "HIGH",
        "priority_label": "Cao",
        "status_code": "OPEN",
        "status_label": "Mới mở",
        "device_code": "PC-ACC-012",
        "device_name": "Dell OptiPlex 7090",
        "device_location": "Phòng Kế toán - Tầng 4",
        "updated_time": "Hôm qua 16:45",
        "updated_note": "Chờ phân công",
        "tech_name": "Chờ phân công",
        "tech_title": "Chờ điều phối",
        "tech_role_short": "Chờ điều phối",
        "tech_initial": "IT",
        "created_at": "11/09/2026 lúc 16:45",
        "creator_name": "Trần Thị Mai (Phòng Kế toán)",
        "description": "Bàn phím không dây Logitech gõ thỉnh thoảng mất tín hiệu, chuột phản hồi chậm.",
    },
    {
        "id": 1039,
        "title": "Cấu hình VPN làm việc từ xa và xác thực 2 bước (2FA)",
        "category_code": "SERVICE_REQUEST",
        "category_label": "Yêu cầu dịch vụ",
        "category_sub": "Mạng & VPN",
        "priority_code": "MEDIUM",
        "priority_label": "Trung bình",
        "status_code": "RESOLVED",
        "status_label": "Đã giải quyết",
        "device_code": "PC-ACC-012",
        "device_name": "Dell Latitude 5420",
        "device_location": "Phòng Kế toán - Tầng 4",
        "updated_time": "10/09/2026",
        "updated_note": "Đã xác nhận hoạt động",
        "tech_name": "Phạm Hoàng Nam",
        "tech_title": "Network Admin",
        "tech_role_short": "Kỹ thuật viên",
        "tech_initial": "HN",
        "created_at": "09/09/2026",
        "creator_name": "Trần Thị Mai (Phòng Kế toán)",
        "description": "Yêu cầu cấp cấu hình FortiClient VPN để làm việc từ xa trong đợt công tác.",
    },
    {
        "id": 1022,
        "title": "Cài đặt bộ phần mềm văn phòng Microsoft Office 365 bản quyền",
        "category_code": "SERVICE_REQUEST",
        "category_label": "Yêu cầu dịch vụ",
        "category_sub": "Phần mềm văn phòng",
        "priority_code": "LOW",
        "priority_label": "Thấp",
        "status_code": "CLOSED",
        "status_label": "Đã đóng",
        "device_code": "PC-ACC-012",
        "device_name": "Dell OptiPlex 7090",
        "device_location": "Phòng Kế toán - Tầng 4",
        "updated_time": "05/09/2026",
        "updated_note": "Đã đánh giá 5 sao",
        "tech_name": "Nguyễn Văn An",
        "tech_title": "Helpdesk L2",
        "tech_role_short": "Kỹ thuật viên",
        "tech_initial": "NA",
        "created_at": "04/09/2026",
        "creator_name": "Trần Thị Mai (Phòng Kế toán)",
        "description": "Cài đặt lại Excel và Outlook bị lỗi add-in chữ ký số.",
    },
]

RECENT_ACTIVITIES = [
    {
        "time": "12 phút trước",
        "ticket_id": "#1048",
        "text": 'Nguyễn Văn An đã cập nhật tiến độ: "Đã kiểm tra switch mạng tầng 4, đang cấu hình lại IP tĩnh."',
    },
    {
        "time": "2 giờ trước",
        "ticket_id": "#1045",
        "text": "Ticket được bàn giao cho chuyên viên Lê Minh Tuấn thẩm định quyền.",
    },
    {
        "time": "Hôm qua",
        "ticket_id": "#1039",
        "text": 'Yêu cầu "Cài đặt VPN làm việc từ xa" đã chuyển sang trạng thái Đã giải quyết.',
    },
    {
        "time": "3 ngày trước",
        "ticket_id": "#1041",
        "text": "Bạn đã tạo mới yêu cầu bảo trì thiết bị ngoại vi văn phòng.",
    },
]
